In [25]:
import numpy as np
import pandas as pd

In [1]:
#turning your data in numbers

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray ( n dimensions array)

In [7]:
a1 = np.array([1,2,3])

In [8]:
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,3.5], [4,5,6.5]])

In [12]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [13]:
a1.shape

(3,)

In [ ]:
# if there is nothing it means 1

In [14]:
a2.shape

(2, 3)

In [17]:
a1.ndim, a2.ndim
#number of dimensions

(1, 2)

In [18]:
a1.dtype

dtype('int32')

In [19]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [20]:
a1.size

3

In [21]:
a2.size

6

In [22]:
#number of total elements in the array

In [23]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [24]:
#Create a DataFrame from a NumPy array

In [26]:
df = pd.DataFrame(a2)

In [27]:
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.5

## Creating arrays

In [29]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [30]:
sample_array.dtype

dtype('int32')

In [33]:
ones = np.ones((2,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
ones.dtype

dtype('int32')

In [35]:
type(ones)

numpy.ndarray

In [36]:
zeros = np.zeros((2,3))

In [37]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
range_array = np.arange(0,10,2, int)

In [41]:
range_array

array([0, 2, 4, 6, 8])

In [45]:
random_array = np.random.randint(0,10,size = (2,2))

In [46]:
random_array

array([[3, 6],
       [5, 7]])

In [47]:
# remember to press shift tab in the parentesis to check the docstring

In [48]:
np.random.random((5,3))

array([[0.56029824, 0.35622466, 0.86593294],
       [0.73915679, 0.92571731, 0.60285674],
       [0.82681497, 0.55747011, 0.46710538],
       [0.1159483 , 0.91616898, 0.86218881],
       [0.43828272, 0.02000049, 0.43277304]])

In [82]:
#pseudo-random numbers
np.random.seed(seed=2)

In [83]:
random_array_4 = np.random.randint(10, size = (5,3))

In [84]:
random_array_4

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

## Viewing array and matrices

In [85]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
a1

array([1, 2, 3])

In [87]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [89]:
a1[0]

1

In [102]:
a4 = np.random.randint(10, size =(2,3,4,5))

In [103]:
a4

array([[[[5, 7, 2, 2, 1],
         [7, 2, 9, 6, 1],
         [3, 5, 7, 5, 7],
         [7, 2, 6, 0, 2]],

        [[7, 1, 6, 9, 5],
         [6, 0, 0, 4, 9],
         [8, 1, 5, 9, 8],
         [3, 1, 1, 6, 9]],

        [[0, 5, 9, 5, 5],
         [9, 6, 8, 1, 8],
         [9, 2, 4, 2, 8],
         [0, 3, 9, 8, 7]]],


       [[[3, 1, 6, 3, 3],
         [1, 9, 8, 8, 3],
         [8, 2, 6, 6, 3],
         [6, 5, 8, 5, 2]],

        [[9, 3, 6, 0, 1],
         [3, 8, 2, 8, 7],
         [8, 7, 5, 5, 1],
         [7, 7, 0, 1, 2]],

        [[8, 1, 0, 1, 0],
         [1, 2, 4, 5, 6],
         [3, 5, 8, 5, 7],
         [8, 8, 8, 3, 2]]]])

In [130]:
a4[:2, :1, :4, :4]

array([[[[5, 7, 2, 2],
         [7, 2, 9, 6],
         [3, 5, 7, 5],
         [7, 2, 6, 0]]],


       [[[3, 1, 6, 3],
         [1, 9, 8, 8],
         [8, 2, 6, 6],
         [6, 5, 8, 5]]]])

## Manipulating & Comparing arrays

### Arithmetic

In [133]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [134]:
a1

array([1, 2, 3])

In [135]:
ones = np.ones(3)

In [136]:
ones

array([1., 1., 1.])

In [137]:
ones + a1

array([2., 3., 4.])

In [138]:
# add elements at the same position

In [139]:
# so, array is good to do arithmetic operations, i believe you cant do that easily with lists or tuples

In [140]:
# c CODE OPTIMIZATION with python vectorization via broadcasting

In [141]:
a2*a1

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [142]:
a1*a2

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [143]:
a1

array([1, 2, 3])

In [144]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [145]:
a3

NameError: name 'a3' is not defined

In [146]:
a4

array([[[[5, 7, 2, 2, 1],
         [7, 2, 9, 6, 1],
         [3, 5, 7, 5, 7],
         [7, 2, 6, 0, 2]],

        [[7, 1, 6, 9, 5],
         [6, 0, 0, 4, 9],
         [8, 1, 5, 9, 8],
         [3, 1, 1, 6, 9]],

        [[0, 5, 9, 5, 5],
         [9, 6, 8, 1, 8],
         [9, 2, 4, 2, 8],
         [0, 3, 9, 8, 7]]],


       [[[3, 1, 6, 3, 3],
         [1, 9, 8, 8, 3],
         [8, 2, 6, 6, 3],
         [6, 5, 8, 5, 2]],

        [[9, 3, 6, 0, 1],
         [3, 8, 2, 8, 7],
         [8, 7, 5, 5, 1],
         [7, 7, 0, 1, 2]],

        [[8, 1, 0, 1, 0],
         [1, 2, 4, 5, 6],
         [3, 5, 8, 5, 7],
         [8, 8, 8, 3, 2]]]])

In [147]:
a1.shape

(3,)

In [148]:
a1

array([1, 2, 3])

In [149]:
a2.shape

(2, 3)

In [150]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [151]:
a5 = np.array([3,6,7])

In [152]:
a5

array([3, 6, 7])

In [153]:
a1*a5

array([ 3, 12, 21])

In [154]:
a5.shape

(3,)

In [155]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [156]:
a2.shape

(2, 3)

In [157]:
random.array

NameError: name 'random' is not defined

In [158]:
random_array

array([[3, 6],
       [5, 7]])

In [159]:
random_array*a1

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [160]:
a2*a1

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [161]:
a1.shape

(3,)

In [162]:
a2.shape

(2, 3)

In [164]:
testarray = np.random.randint(10, size = (4,3))

In [165]:
testarray

array([[3, 0, 5],
       [3, 7, 2],
       [4, 7, 9],
       [6, 1, 9]])

In [167]:
testarray * a1

array([[ 3,  0, 15],
       [ 3, 14,  6],
       [ 4, 14, 27],
       [ 6,  2, 27]])

In [168]:
testarray * 2

array([[ 6,  0, 10],
       [ 6, 14,  4],
       [ 8, 14, 18],
       [12,  2, 18]])

In [169]:
# just tested a lot of arithmetical operations with numpy, no need to write everything because i would need to look for it anyway

In [170]:
#use python's methods on python data types and numpys methods on numpy arrays

In [171]:
massive_array = np.random.random(100000)

In [172]:
massive_array[:100]

array([0.13939856, 0.96763911, 0.38936172, 0.44502664, 0.64714426,
       0.44848938, 0.45280457, 0.68124203, 0.68626121, 0.96700146,
       0.14081288, 0.55152478, 0.55414633, 0.00963502, 0.18502232,
       0.34048119, 0.31303354, 0.71839106, 0.37903173, 0.1159734 ,
       0.00722843, 0.84905058, 0.04237171, 0.17513312, 0.01762698,
       0.99429144, 0.34460346, 0.62093856, 0.49480627, 0.80928738,
       0.598676  , 0.90877359, 0.43777264, 0.56203935, 0.18660879,
       0.70948564, 0.87611891, 0.33549495, 0.85746507, 0.28727814,
       0.25946458, 0.65565793, 0.05177355, 0.91063937, 0.63482783,
       0.65148817, 0.91122351, 0.40970761, 0.35710262, 0.87499249,
       0.39478505, 0.76032504, 0.76439114, 0.86950785, 0.09941022,
       0.80172872, 0.7049072 , 0.52608091, 0.36460034, 0.54698354,
       0.08810252, 0.42692006, 0.29163754, 0.05758539, 0.75463489,
       0.47893896, 0.6112719 , 0.19712341, 0.81814991, 0.53513907,
       0.9954019 , 0.14269152, 0.14576616, 0.8560753 , 0.36988

In [176]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

8.87 ms ± 370 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
57.8 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [177]:
a2.mean

<function ndarray.mean>

In [178]:
np.mean(a2)

3.6666666666666665

In [179]:
np.max(a2)

6.5

In [180]:
np.min(a2)

1.0

In [181]:
np.std(a2) # = how spread out a group of number is from the mean, ( the mean of how spread out they are)

1.818118685772619

In [182]:
np.var(a2) # Variance = Higer variance = wider range of numbers

3.305555555555556

In [183]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [185]:
a2.shape

(2, 3)

In [190]:
a2_1 = a2.reshape(3,2)

In [191]:
a2_1

array([[1. , 2. ],
       [3.5, 4. ],
       [5. , 6.5]])

In [192]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [193]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.5, 6.5]])

In [194]:
# dot product
#np.dot(matriz1, matriz2)
#make a dot mat multiplication, its different than element wise

## Dot product example

In [197]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size= (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [199]:
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [200]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [217]:
# Create prices array

price_amounts = np.array([10,8,12])

In [218]:
price_amounts.shape

(3,)

In [219]:
price_sales = pd.DataFrame(price_amounts.reshape(1,3), index = ["Price"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [236]:
price_sales

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [237]:
testx = np.dot(sales_amounts, price_amounts).reshape(5,1)
testx

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [248]:
daily_sales = price_sales.dot(weekly_sales.T)

In [249]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [257]:
# i managed to build a data frame from different data frames using df.dot(df2)


In [260]:
testdf = pd.DataFrame(testx, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], columns = ["Price"])

In [261]:
testdf

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [253]:
weekly_sales["Total"] = (daily_sales.T)

In [255]:
weekly_sales["Teste"] = (testx)

In [256]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total  Teste
Mon               12             15              0    240    240
Tues               3              3              7    138    138
Wed                9             19             18    458    458
Thurs              4              6             12    232    232
Fri                1              6              7    142    142

### Comparions Operators

In [263]:
a1

array([1, 2, 3])

In [264]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [266]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [267]:
#just like normal python

## Sorting arrays

In [270]:
random_array1 = np.random.randint(10, size=(3,5) )

In [271]:
random_array

array([[3, 6],
       [5, 7]])

In [272]:
random_array1

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [273]:
np.sort(random_array1)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [275]:
np.argsort(random_array1)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

## Practical Example

In [276]:
# Turn an image into a NumPy array

In [291]:
from matplotlib.image import imread

In [292]:
panda = imread("panda.png")

In [293]:
type(panda)

numpy.ndarray

In [294]:
panda.size

24465000

In [295]:
panda.shape

(2330, 3500, 3)

In [297]:
panda.ndim

3

In [298]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="panda.png">

In [300]:
car = imread("car-photo.png")

In [303]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src ="dog-photo.png">

In [304]:
dog = imread("dog-photo.png")

In [305]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

In [306]:
#turning images in data