In [1]:
import numpy as np
import pandas as pd

In [2]:
#turning your data in numbers

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray ( n dimensions array)

In [4]:
a1 = np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3.5], [4,5,6.5]])

In [8]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [9]:
a1.shape

(3,)

In [10]:
# if there is nothing it means 1

In [11]:
a2.shape

(2, 3)

In [12]:
a1.ndim, a2.ndim
#number of dimensions

(1, 2)

In [13]:
a1.dtype

dtype('int32')

In [14]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [15]:
a1.size

3

In [16]:
a2.size

6

In [17]:
#number of total elements in the array

In [18]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [19]:
#Create a DataFrame from a NumPy array

In [20]:
df = pd.DataFrame(a2)

In [21]:
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.5

## Creating arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int32')

In [24]:
ones = np.ones((2,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
ones.dtype

dtype('int32')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2,3))

In [28]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2, int)

In [30]:
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0,10,size = (2,2))

In [32]:
random_array

array([[9, 2],
       [3, 7]])

In [33]:
# remember to press shift tab in the parentesis to check the docstring

In [34]:
np.random.random((5,3))

array([[0.64543227, 0.05298962, 0.9249666 ],
       [0.15759082, 0.63502354, 0.82563309],
       [0.56644504, 0.55553299, 0.70366396],
       [0.49558772, 0.7529563 , 0.87986425],
       [0.60932962, 0.01994908, 0.66099058]])

In [35]:
#pseudo-random numbers
np.random.seed(seed=2)

In [36]:
random_array_4 = np.random.randint(10, size = (5,3))

In [37]:
random_array_4

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

## Viewing array and matrices

In [38]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [41]:
a1[0]

1

In [42]:
a4 = np.random.randint(10, size =(2,3,4,5))

In [43]:
a4

array([[[[4, 3, 7, 6, 1],
         [3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8]],

        [[2, 9, 8, 7, 1],
         [6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6]],

        [[5, 6, 6, 6, 3],
         [8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4]]],


       [[[5, 8, 3, 0, 0],
         [5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0]],

        [[8, 5, 4, 2, 9],
         [7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2]],

        [[5, 1, 3, 3, 1],
         [8, 6, 8, 1, 5],
         [7, 0, 9, 1, 5],
         [9, 2, 0, 0, 4]]]])

In [44]:
a4[:2, :1, :4, :4]

array([[[[4, 3, 7, 6],
         [3, 5, 8, 4],
         [3, 9, 2, 0],
         [2, 4, 1, 7]]],


       [[[5, 8, 3, 0],
         [5, 7, 5, 0],
         [6, 5, 1, 7],
         [3, 6, 1, 4]]]])

## Manipulating & Comparing arrays

### Arithmetic

In [45]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
a1

array([1, 2, 3])

In [47]:
ones = np.ones(3)

In [48]:
ones

array([1., 1., 1.])

In [49]:
ones + a1

array([2., 3., 4.])

In [50]:
# add elements at the same position

In [51]:
# so, array is good to do arithmetic operations, i believe you cant do that easily with lists or tuples

In [52]:
# c CODE OPTIMIZATION with python vectorization via broadcasting

In [53]:
a2*a1

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [54]:
a1*a2

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [55]:
a1

array([1, 2, 3])

In [56]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [57]:
a4

array([[[[4, 3, 7, 6, 1],
         [3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8]],

        [[2, 9, 8, 7, 1],
         [6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6]],

        [[5, 6, 6, 6, 3],
         [8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4]]],


       [[[5, 8, 3, 0, 0],
         [5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0]],

        [[8, 5, 4, 2, 9],
         [7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2]],

        [[5, 1, 3, 3, 1],
         [8, 6, 8, 1, 5],
         [7, 0, 9, 1, 5],
         [9, 2, 0, 0, 4]]]])

In [58]:
a1.shape

(3,)

In [59]:
a1

array([1, 2, 3])

In [60]:
a2.shape

(2, 3)

In [61]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [62]:
a5 = np.array([3,6,7])

In [63]:
a5

array([3, 6, 7])

In [64]:
a1*a5

array([ 3, 12, 21])

In [65]:
a5.shape

(3,)

In [66]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [67]:
a2.shape

(2, 3)

In [68]:
random_array

array([[9, 2],
       [3, 7]])

In [69]:
a2*a1

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [70]:
a1.shape

(3,)

In [71]:
a2.shape

(2, 3)

In [72]:
testarray = np.random.randint(10, size = (4,3))

In [73]:
testarray

array([[6, 3, 1],
       [8, 5, 9],
       [5, 4, 2],
       [7, 8, 7]])

In [74]:
testarray * a1

array([[ 6,  6,  3],
       [ 8, 10, 27],
       [ 5,  8,  6],
       [ 7, 16, 21]])

In [75]:
testarray * 2

array([[12,  6,  2],
       [16, 10, 18],
       [10,  8,  4],
       [14, 16, 14]])

In [76]:
# just tested a lot of arithmetical operations with numpy, no need to write everything.

In [77]:
#use python's methods on python data types and numpys methods on numpy arrays

In [78]:
massive_array = np.random.random(100000)

In [79]:
massive_array[:100]

array([0.11058315, 0.27405925, 0.01025004, 0.62935972, 0.29517231,
       0.18728654, 0.09528805, 0.28375581, 0.21492438, 0.28560373,
       0.47140986, 0.54949682, 0.84511312, 0.9885097 , 0.04886809,
       0.23211825, 0.64331143, 0.16146656, 0.87014589, 0.21740243,
       0.74175504, 0.65302051, 0.79888551, 0.03124756, 0.22957403,
       0.7046275 , 0.08756251, 0.03058948, 0.35713493, 0.58978199,
       0.05222273, 0.06566367, 0.04350119, 0.39515076, 0.66842705,
       0.19802711, 0.87626645, 0.4323891 , 0.61964146, 0.29042674,
       0.61525457, 0.95365996, 0.44801472, 0.20704984, 0.42536729,
       0.44457426, 0.50761749, 0.52573325, 0.04242919, 0.16441909,
       0.45022718, 0.70797117, 0.77758791, 0.777103  , 0.50277875,
       0.95674759, 0.33187371, 0.48145816, 0.748374  , 0.85783952,
       0.41446006, 0.84868451, 0.44457094, 0.71574708, 0.00844836,
       0.02520142, 0.94045049, 0.10213795, 0.66196779, 0.28325874,
       0.20084234, 0.38833418, 0.9259016 , 0.57027421, 0.91671

In [80]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

7.36 ms ± 117 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.4 µs ± 893 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [81]:
a2.mean

<function ndarray.mean>

In [82]:
np.mean(a2)

3.6666666666666665

In [83]:
np.max(a2)

6.5

In [84]:
np.min(a2)

1.0

In [85]:
np.std(a2) # = how spread out a group of number is from the mean, ( the mean of how spread out they are)

1.818118685772619

In [86]:
np.var(a2) # Variance = Higer variance = wider range of numbers

3.305555555555556

In [87]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [88]:
a2.shape

(2, 3)

In [89]:
a2_1 = a2.reshape(3,2)

In [90]:
a2_1

array([[1. , 2. ],
       [3.5, 4. ],
       [5. , 6.5]])

In [91]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [92]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.5, 6.5]])

In [93]:
# dot product
#np.dot(matriz1, matriz2)
#make a dot mat multiplication, its different than element wise

## Dot product example

In [94]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size= (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [95]:
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [96]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [97]:
# Create prices array

price_amounts = np.array([10,8,12])

In [98]:
price_amounts.shape

(3,)

In [99]:
price_sales = pd.DataFrame(price_amounts.reshape(1,3), index = ["Price"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [100]:
price_sales

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [101]:
testx = np.dot(sales_amounts, price_amounts).reshape(5,1)
testx

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [102]:
daily_sales = price_sales.dot(weekly_sales.T)

In [103]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [104]:
# i managed to build a data frame from different data frames using df.dot(df2)


In [105]:
testdf = pd.DataFrame(testx, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], columns = ["Price"])

In [106]:
testdf

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [107]:
weekly_sales["Total"] = (daily_sales.T)

In [108]:
weekly_sales["Teste"] = (testx)

In [109]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total  Teste
Mon               12             15              0    240    240
Tues               3              3              7    138    138
Wed                9             19             18    458    458
Thurs              4              6             12    232    232
Fri                1              6              7    142    142

### Comparions Operators

In [110]:
a1

array([1, 2, 3])

In [111]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [112]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

## Sorting arrays

In [113]:
random_array1 = np.random.randint(10, size=(3,5) )

In [114]:
random_array

array([[9, 2],
       [3, 7]])

In [115]:
random_array1

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [116]:
np.sort(random_array1)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [117]:
np.argsort(random_array1)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

## Practical Example

In [118]:
# Turn an image into a NumPy array

In [119]:
from matplotlib.image import imread

In [120]:
panda = imread("panda.png")

FileNotFoundError: [Errno 2] No such file or directory: 'panda.png'

In [ ]:
type(panda)

numpy.ndarray

In [ ]:
panda.size

24465000

In [ ]:
panda.shape

(2330, 3500, 3)

In [ ]:
panda.ndim

3

In [ ]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="panda.png">

In [ ]:
car = imread("car-photo.png")

In [ ]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src ="dog-photo.png">

In [ ]:
dog = imread("dog-photo.png")

In [ ]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

In [ ]:
#turning images in data